name: fast_api_training
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - ipykernel
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - pyarrow
  - fastapi
  - uvicorn
  - requests
  - httpx
  - pydantic
  - pillow
  - boto3
  - pytest
  - streamlit
  - protobuf=3.20.3
